version: "3.7"

services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile-devbox
    volumes:
      - type: bind
        source: ./examples
        target: /var/app/examples
      - type: bind
        source: ./src
        target: /var/app/src
      - type: bind
        source: ./tests
        target: /var/app/tests
  tox:
    build:
      context: .
      dockerfile: Dockerfile-tox
    working_dir: /docker
    command: tox
    volumes:
      - type: bind
        source: .
        target: /docker
